import type {Metadata} from "next";
import "./globals.css";
import AppLayoutProvider from "@/context/AppLayoutProvider";
import {WorkspaceProvider} from "@/context/WorkspaceProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <WorkspaceProvider>
            <AppLayoutProvider>
                {children}
            </AppLayoutProvider>
        </WorkspaceProvider>
        </html>
    );
}
